std_msgs/Header header

float64 latitude   # 改为双精度
float64 longitude  # 改为双精度
float64 height     # 改为双精度
float32 vel_e
float32 vel_n
float32 vel_u
float32 pitch
float32 roll
float32 yaw
uint8   ins_status
uint16  gnss_week
uint32  gnss_second
uint8   gnss_status
uint8   satellite_main
uint8   satellite_sub
float32 imu_acc_x
float32 imu_acc_y
float32 imu_acc_z
float32 imu_gyro_x
float32 imu_gyro_y
float32 imu_gyro_z
float32 imu_temp
float32 accuracy_horizon
float32 accuracy_height
float32 accuracy_horizon_velocity
float32 accuracy_vertical_velocity
float32 accuracy_horizon_posture
float32 accuracy_yaw